import type { Locale } from './types';

const messages = {
  en: {
    localeCode: 'en-US', servers: 'Servers', myProfiles: 'My Profiles', settings: 'Settings', valheim: 'Valheim', community: 'Community',
    loadingLauncher: 'Loading launcher…', loading: 'Loading…', refresh: 'Refresh', close: 'Close', gameMissing: 'Valheim was not detected. Choose the game executable in Settings.',
    chooseServer: 'Choose a server', serverPageDescription: 'Pick a Xóm Nghiện server. The launcher handles its required mods and connection details.', noServers: 'No servers available', noServersDescription: 'No launcher-ready Valheim servers are currently available.',
    online: 'Online', offline: 'Offline', unknown: 'Unknown', mods: 'mods', required: 'Required', optional: 'Optional', serverDescriptionFallback: 'A community Valheim server.',
    vietnameseTranslation: 'Vietnamese translation', playInVietnamese: 'Khám phá Valheim bằng tiếng Việt', translationDescription: 'Install the community Vietnamese language pack in one click and enjoy clearer menus, items, biomes, and skills.', translationAttribution: 'Community translation by Vietnamgang · Installed from Thunderstore', installToProfile: 'Install to', newDefaultProfile: 'New Default profile', installVietnamese: 'Install Vietnamese', installingVietnamese: 'Installing Vietnamese translation…',
    automaticConnect: 'Automatic connection', readyToPlay: 'Ready to play?', connectDescription: 'The launcher synchronizes this server profile and opens Valheim for you.', syncAndPlay: 'Sync & Play', syncing: 'Synchronizing profile…', manualConnect: 'Manual connection', serverAddress: 'Server address', password: 'Password', passwordUnavailable: 'Could not load', copied: 'Copied',
    personalProfiles: 'Personal profiles', profilesDescription: 'Build separate mod setups for solo worlds or any server you choose.', importProfile: 'Import profile', createProfile: 'Create profile', noPersonalProfiles: 'No personal profiles yet', noPersonalProfilesDescription: 'Create a profile to build your own Valheim mod setup, or import one from r2modman.', createFirstProfile: 'Create your first profile',
    changesPending: 'Changes pending', notInstalled: 'Not installed', ready: 'Ready', dependencies: 'dependencies', lastSynced: 'Last synced', neverSynced: 'Never synchronized', moreActions: 'More actions', rename: 'Rename', renameProfile: 'Rename profile', exportProfile: 'Export profile', openFolder: 'Open folder', repair: 'Repair', deleteProfile: 'Delete profile', installed: 'Installed', discoverMods: 'Discover mods',
    profileNotInstalled: 'Profile is not installed', profileNotInstalledDescription: 'Synchronize once to prepare BepInEx and this profile’s mods.', changesPendingDescription: 'Synchronize to apply your latest mod choices before playing.', syncNow: 'Sync now',
    noModsInstalled: 'No mods selected', noModsInstalledDescription: 'Open Discover mods to add your first mod. BepInEx is prepared automatically.', pending: 'Pending', remove: 'Remove', search: 'Search Thunderstore…', downloadsLabel: 'downloads', deprecated: 'Deprecated', added: 'Added', update: 'Update', add: 'Add', noModsFound: 'No mods found', tryAnotherSearch: 'Try another name, author, or keyword.',
    creatingProfile: 'Creating profile…', createProfileDescription: 'Profiles keep their mods isolated from Valheim and from each other.', profileName: 'Profile name', cancel: 'Cancel', create: 'Create', renamingProfile: 'Renaming profile…', save: 'Save', deleteProfileDescription: 'This permanently removes the profile and its installed files:', deletingProfile: 'Deleting profile…', delete: 'Delete',
    readingProfile: 'Reading profile…', importingProfile: 'Importing profile…', importPrivacyNotice: 'Only mod names, versions, and enabled states are imported. Bundled configs and other files are ignored.', enabled: 'Enabled', disabled: 'Disabled', unavailable: 'Unavailable', import: 'Import', exportingProfile: 'Exporting profile…', repairingProfile: 'Repairing profile…', enabling: 'Enabling', disabling: 'Disabling', removing: 'Removing', adding: 'Adding',
    websiteApiUrl: 'Website API URL', valheimExecutable: 'Valheim executable', chooseValheimExecutable: 'Choose Valheim executable', language: 'Language', concurrentDownloads: 'Concurrent downloads', launchArguments: 'Additional launch arguments', minimizeOnLaunch: 'Minimize launcher when Valheim starts', checkForUpdates: 'Check for launcher updates', savingSettings: 'Saving settings…', clearCache: 'Clear cache', clearingCache: 'Clearing cache…', openLogs: 'Open logs',
  },
  vi: {
    localeCode: 'vi-VN', servers: 'Máy chủ', myProfiles: 'Hồ sơ của tôi', settings: 'Cài đặt', valheim: 'Valheim', community: 'Cộng đồng',
    loadingLauncher: 'Đang tải launcher…', loading: 'Đang tải…', refresh: 'Làm mới', close: 'Đóng', gameMissing: 'Không tìm thấy Valheim. Hãy chọn tệp trò chơi trong Cài đặt.',
    chooseServer: 'Chọn máy chủ', serverPageDescription: 'Chọn máy chủ Xóm Nghiện. Launcher sẽ xử lý mod bắt buộc và thông tin kết nối.', noServers: 'Không có máy chủ', noServersDescription: 'Hiện chưa có máy chủ Valheim nào sẵn sàng cho launcher.',
    online: 'Trực tuyến', offline: 'Ngoại tuyến', unknown: 'Chưa rõ', mods: 'mod', required: 'Bắt buộc', optional: 'Tùy chọn', serverDescriptionFallback: 'Máy chủ Valheim cộng đồng.',
    vietnameseTranslation: 'Bản dịch tiếng Việt', playInVietnamese: 'Khám phá Valheim bằng tiếng Việt', translationDescription: 'Cài gói ngôn ngữ tiếng Việt cộng đồng chỉ với một lần nhấn để hiểu rõ menu, vật phẩm, quần xã và kỹ năng.', translationAttribution: 'Bản dịch cộng đồng bởi Vietnamgang · Cài đặt từ Thunderstore', installToProfile: 'Cài vào', newDefaultProfile: 'Hồ sơ Default mới', installVietnamese: 'Cài tiếng Việt', installingVietnamese: 'Đang cài bản dịch tiếng Việt…',
    automaticConnect: 'Kết nối tự động', readyToPlay: 'Sẵn sàng chơi?', connectDescription: 'Launcher sẽ đồng bộ hồ sơ máy chủ và mở Valheim cho bạn.', syncAndPlay: 'Đồng bộ & Chơi', syncing: 'Đang đồng bộ hồ sơ…', manualConnect: 'Kết nối thủ công', serverAddress: 'Địa chỉ máy chủ', password: 'Mật khẩu', passwordUnavailable: 'Không thể tải', copied: 'Đã sao chép',
    personalProfiles: 'Hồ sơ cá nhân', profilesDescription: 'Tạo các bộ mod riêng cho thế giới cá nhân hoặc máy chủ bạn chọn.', importProfile: 'Nhập hồ sơ', createProfile: 'Tạo hồ sơ', noPersonalProfiles: 'Chưa có hồ sơ cá nhân', noPersonalProfilesDescription: 'Tạo hồ sơ để xây dựng bộ mod Valheim riêng hoặc nhập hồ sơ từ r2modman.', createFirstProfile: 'Tạo hồ sơ đầu tiên',
    changesPending: 'Có thay đổi', notInstalled: 'Chưa cài đặt', ready: 'Sẵn sàng', dependencies: 'phụ thuộc', lastSynced: 'Đồng bộ lần cuối', neverSynced: 'Chưa từng đồng bộ', moreActions: 'Thao tác khác', rename: 'Đổi tên', renameProfile: 'Đổi tên hồ sơ', exportProfile: 'Xuất hồ sơ', openFolder: 'Mở thư mục', repair: 'Sửa chữa', deleteProfile: 'Xóa hồ sơ', installed: 'Đã chọn', discoverMods: 'Khám phá mod',
    profileNotInstalled: 'Hồ sơ chưa được cài đặt', profileNotInstalledDescription: 'Đồng bộ một lần để chuẩn bị BepInEx và các mod của hồ sơ.', changesPendingDescription: 'Đồng bộ để áp dụng lựa chọn mod mới nhất trước khi chơi.', syncNow: 'Đồng bộ ngay',
    noModsInstalled: 'Chưa chọn mod', noModsInstalledDescription: 'Mở Khám phá mod để thêm mod đầu tiên. BepInEx được chuẩn bị tự động.', pending: 'Chờ đồng bộ', remove: 'Gỡ', search: 'Tìm trên Thunderstore…', downloadsLabel: 'lượt tải', deprecated: 'Đã ngừng hỗ trợ', added: 'Đã thêm', update: 'Cập nhật', add: 'Thêm', noModsFound: 'Không tìm thấy mod', tryAnotherSearch: 'Thử tên, tác giả hoặc từ khóa khác.',
    creatingProfile: 'Đang tạo hồ sơ…', createProfileDescription: 'Mỗi hồ sơ giữ mod tách biệt khỏi Valheim và các hồ sơ khác.', profileName: 'Tên hồ sơ', cancel: 'Hủy', create: 'Tạo', renamingProfile: 'Đang đổi tên hồ sơ…', save: 'Lưu', deleteProfileDescription: 'Thao tác này sẽ xóa vĩnh viễn hồ sơ và các tệp đã cài:', deletingProfile: 'Đang xóa hồ sơ…', delete: 'Xóa',
    readingProfile: 'Đang đọc hồ sơ…', importingProfile: 'Đang nhập hồ sơ…', importPrivacyNotice: 'Chỉ tên mod, phiên bản và trạng thái bật/tắt được nhập. Cấu hình và các tệp khác sẽ bị bỏ qua.', enabled: 'Đang bật', disabled: 'Đang tắt', unavailable: 'Không khả dụng', import: 'Nhập', exportingProfile: 'Đang xuất hồ sơ…', repairingProfile: 'Đang sửa hồ sơ…', enabling: 'Đang bật', disabling: 'Đang tắt', removing: 'Đang gỡ', adding: 'Đang thêm',
    websiteApiUrl: 'URL API trang web', valheimExecutable: 'Tệp thực thi Valheim', chooseValheimExecutable: 'Chọn tệp thực thi Valheim', language: 'Ngôn ngữ', concurrentDownloads: 'Số lượt tải đồng thời', launchArguments: 'Tham số khởi chạy bổ sung', minimizeOnLaunch: 'Thu nhỏ launcher khi Valheim khởi động', checkForUpdates: 'Kiểm tra cập nhật launcher', savingSettings: 'Đang lưu cài đặt…', clearCache: 'Xóa bộ nhớ đệm', clearingCache: 'Đang xóa bộ nhớ đệm…', openLogs: 'Mở nhật ký',
  },
} as const;

export type MessageKey = keyof typeof messages.en;
export function translator(locale: Locale) {
  return (key: MessageKey) => messages[locale][key] || messages.en[key];
}
